# Configuration for the roar CLI
# https://github.com/JanMalch/roar

[[update]]
file = "gradle.properties"
find = "version="
replace = "version={{version}}"

[[update]]
file = "README.md"
find = "implementation(\"io.github.janmalch:ktor-revfile-core:"
replace = "implementation(\"io.github.janmalch:ktor-revfile-core:{{version}}\")"

[[update]]
file = "README.md"
find = "implementation(\"io.github.janmalch:ktor-revfile-html:"
replace = "implementation(\"io.github.janmalch:ktor-revfile-html:{{version}}\") // add for kotlinx.html interop"

[changelog]
include = ["feat", "fix", "refactor"]
url_commit = "https://github.com/JanMalch/ktor-revfile/commit/{{hash}}"
url_browse_at_tag = "https://github.com/JanMalch/ktor-revfile/tree/v{{version}}"
url_compare_tags = "https://github.com/JanMalch/ktor-revfile/compare/v{{previous}}...v{{version}}"
url_commits_for_tag = "https://github.com/JanMalch/ktor-revfile/commits/v{{version}}"
