name: Deploy to central

on: workflow_dispatch

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build.yml
  deploy:
    needs: build
    strategy:
      matrix:
        include:
          - target: publishJvmPublicationToSonatypeRepository
            os: ubuntu-latest
          - target: publishLinuxX64PublicationToSonatypeRepository
            os: ubuntu-latest
          - target: publishKotlinMultiplatformPublicationToSonatypeRepository
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - uses: actions/cache@v4
        with:
          path: |
            ~/.konan
          key: ${{ runner.os }}-${{ hashFiles('**/.lock') }}
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          passphrase: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Gradle publish
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: |
            ${{ matrix.target }}
            closeSonatypeStagingRepository
            -Psigning.gnupg.passphrase='${{secrets.OSSRH_GPG_SECRET_KEY_PASSWORD}}'
            -Psigning.gnupg.keyName='${{secrets.OSSRH_GPG_SECRET_KEY_ID}}'
            -PsonatypeUsername='${{secrets.OSSRH_USERNAME}}'
            -PsonatypePassword='${{secrets.OSSRH_PASSWORD}}'

